name: release

on:
  release:
    types:
      - published

jobs:
  publish:
    name:    publish
    runs-on: ubuntu-latest
    steps:

      - name: checkout
        uses: actions/checkout@v2

      - name: install Node
        uses: actions/setup-node@v1
        with:
          node-version: 14.x

      - name: install packages
        run:  npm ci

      - name: build docs
        run:  npm run docs

      - name: publish to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir:  ./docs
