name: test

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  run-tests:
    name:    run tests
    runs-on: ubuntu-latest
    steps:

      - name: checkout
        uses: actions/checkout@v2

      - name: set up Node for npm
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
          registry-url: https://registry.npmjs.org/

      - name: install dependencies
        run:  npm ci

      - name: run tests
        run:  npm test
